/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "surface-bright": "#363942",
        "on-secondary-container": "#00311f",
        "on-secondary-fixed-variant": "#005236",
        "on-background": "#e0e2ed",
        "outline-variant": "#414755",
        "sleep": "#6366F1",
        "on-primary-container": "#00285c",
        "primary": "#adc6ff",
        "fitness": "#10B981",
        "secondary": "#4edea3",
        "inverse-surface": "#e0e2ed",
        "nutrition": "#F59E0B",
        "surface": "#10131b",
        "supplement": "#A855F7",
        "on-error-container": "#ffdad6",
        "surface-container-highest": "#31353d",
        "error-container": "#93000a",
        "on-secondary-fixed": "#002113",
        "surface-tint": "#adc6ff",
        "on-primary-fixed": "#001a41",
        "surface-container-lowest": "#0b0e16",
        "on-primary-fixed-variant": "#004493",
        "surface-dark": "#171717",
        "outline": "#8b90a0",
        "on-tertiary-container": "#4c1a00",
        "on-error": "#690005",
        "surface-variant": "#31353d",
        "tertiary-fixed": "#ffdbcc",
        "surface-container": "#1c2028",
        "secondary-container": "#00a572",
        "surface-container-high": "#272a32",
        "inverse-primary": "#005bc1",
        "border-dark": "#262626",
        "error": "#ffb4ab",
        "on-secondary": "#003824",
        "secondary-fixed-dim": "#4edea3",
        "tertiary": "#ffb595",
        "primary-fixed": "#d8e2ff",
        "on-primary": "#002e69",
        "background-dark": "#0A0A0A",
        "on-surface-variant": "#c1c6d7",
        "on-tertiary": "#571e00",
        "primary-container": "#4b8eff",
        "primary-fixed-dim": "#adc6ff",
        "tertiary-container": "#ef6719",
        "on-tertiary-fixed-variant": "#7c2e00",
        "background": "#10131b",
        "secondary-fixed": "#6ffbbe",
        "on-tertiary-fixed": "#351000",
        "surface-container-low": "#181c23",
        "surface-dim": "#10131b",
        "on-surface": "#e0e2ed",
        "tertiary-fixed-dim": "#ffb595",
        "inverse-on-surface": "#2d3039"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "element-gap": "0.75rem",
        "stack-gap": "1.5rem",
        "touch-target-min": "44px",
        "container-margin": "1.25rem",
        "telegram-bottom-safe": "56px"
      },
      fontFamily: {
        "body-sm": ["Inter"],
        "mono-data": ["Geist"],
        "headline-md": ["Geist"],
        "label-caps": ["Geist"],
        "stat-lg": ["Geist"],
        "body-base": ["Inter"],
        "stat-hero": ["Geist"]
      },
      fontSize: {
        "body-sm": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "mono-data": ["14px", { "lineHeight": "14px", "fontWeight": "500" }],
        "headline-md": ["20px", { "lineHeight": "28px", "fontWeight": "600" }],
        "label-caps": ["12px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600" }],
        "stat-lg": ["32px", { "lineHeight": "32px", "letterSpacing": "-0.02em", "fontWeight": "600" }],
        "body-base": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "stat-hero": ["48px", { "lineHeight": "48px", "letterSpacing": "-0.05em", "fontWeight": "700" }]
      }
    },
  },
  plugins: [],
}
